---
- hosts: server
  vars:
    foo:
      - name: tree
      - name: tree1
  tasks:
    - name: oinstall a packahe
      yum:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ foo }}"
